---
- hosts: all
  tasks:
    - name: ensure nginx is at the latest version
      apt: name=nginx state=latest
      become: yes
    - name: start nginx
      service:
          name: nginx
          state: started
      become: yes
    - name: copy the index page content
      copy: 
        src: index.html
        dest: /var/www/html/index.html
      become: yes
    - name: restart nginx
      service:
        name: nginx
        state: restarted
      become: yes